version: 2.1

orbs:
  maven: circleci/maven@1.3.0

workflows:
  maven_test:
    jobs:
      - maven/test: # checkout, build, test, and upload test results
          command: 'test -Dsuite=Runner -DtestSuiteTemplate=SmokeSuite -Dlocal=false -Dbs.enabled=true -Dusername=vinhnguyen5 -DaccessKey=BGXjQCA1xCVc7JKsh2ez'
