name: Maven Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v1
      with:
       path: ~/.m2/repository
       key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
       restore-keys: |
         ${{ runner.os }}-maven-
    - name: Install and Run Appium Server
      uses: moatazeldebsy/appium-server-gitHub-action@V1.0.5
    - name: Set environment variables
      run: |
        export BROWSERSTACK_USERNAME=vinhnguyen5
        export BROWSERSTACK_ACCESS_KEY=BGXjQCA1xCVc7JKsh2ez
    - name: Build with Maven
      run: mvn clean test -Dsuite=Runner -DtestSuiteTemplate=SmokeSuite -Dbs.enabled=true -Dlocal=false
